AWSTemplateFormatVersion: '2010-09-09'
Description: 'Okiteru - Authentication Layer (Cognito)'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name

  FrontendDomain:
    Type: String
    Description: Frontend domain (e.g., https://okiteru.example.com)

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${EnvironmentName}-okiteru-users
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: phone_number
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: role
          AttributeDataType: String
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      UserPoolTags:
        Name: !Sub ${EnvironmentName}-okiteru-user-pool

  # User Pool Domain
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${EnvironmentName}-okiteru-${AWS::AccountId}
      UserPoolId: !Ref UserPool

  # User Pool Client (Web)
  UserPoolClientWeb:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${EnvironmentName}-okiteru-web-client
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      RefreshTokenValidity: 30
      AccessTokenValidity: 1
      IdTokenValidity: 1
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: hours
        IdToken: hours
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - !Ref FrontendDomain
        - !Sub ${FrontendDomain}/callback
        - http://localhost:3000
        - http://localhost:3000/callback
      LogoutURLs:
        - !Ref FrontendDomain
        - http://localhost:3000
      SupportedIdentityProviders:
        - COGNITO

  # User Pool Groups
  StaffGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: staff
      Description: Staff users group
      UserPoolId: !Ref UserPool
      Precedence: 10

  ManagerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: manager
      Description: Manager users group
      UserPoolId: !Ref UserPool
      Precedence: 5

  # Identity Pool
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub ${EnvironmentName}_okiteru_identity_pool
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClientWeb
          ProviderName: !GetAtt UserPool.ProviderName

  # IAM Roles for Identity Pool
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-okiteru-cognito-authenticated
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-identity:GetCredentialsForIdentity
                  - cognito-identity:GetId
                Resource: '*'

  # Identity Pool Role Attachment
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-user-pool-id

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-user-pool-arn

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClientWeb
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-user-pool-client-id

  UserPoolDomain:
    Description: Cognito User Pool Domain
    Value: !Ref UserPoolDomain
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-user-pool-domain

  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-identity-pool-id

  CognitoAuthenticatedRoleArn:
    Description: IAM Role ARN for authenticated users
    Value: !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-cognito-auth-role-arn
