AWSTemplateFormatVersion: '2010-09-09'
Description: 'Okiteru - CloudFront Distribution Layer'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: Environment name

  CustomDomain:
    Type: String
    Default: ''
    Description: Custom domain name (optional, e.g., okiteru.example.com)

  ACMCertificateArn:
    Type: String
    Default: ''
    Description: ACM Certificate ARN for custom domain (must be in us-east-1)

Conditions:
  HasCustomDomain: !Not [!Equals [!Ref CustomDomain, '']]
  HasCertificate: !Not [!Equals [!Ref ACMCertificateArn, '']]

Resources:
  # CloudFront Origin Access Control for S3
  FrontendOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${EnvironmentName}-okiteru-frontend-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  PhotosOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub ${EnvironmentName}-okiteru-photos-oac
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution for Frontend & API
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub ${EnvironmentName} Okiteru Distribution
        HttpVersion: http2and3
        IPV6Enabled: true
        PriceClass: PriceClass_All
        Aliases: !If
          - HasCustomDomain
          - [!Ref CustomDomain]
          - !Ref AWS::NoValue
        ViewerCertificate: !If
          - HasCertificate
          - AcmCertificateArn: !Ref ACMCertificateArn
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
          - CloudFrontDefaultCertificate: true

        # Origins
        Origins:
          # Frontend S3 Origin
          - Id: FrontendS3Origin
            DomainName:
              Fn::Sub:
                - ${BucketName}.s3.${AWS::Region}.amazonaws.com
                - BucketName:
                    Fn::ImportValue: !Sub ${EnvironmentName}-okiteru-frontend-bucket-name
            OriginAccessControlId: !Ref FrontendOAC
            S3OriginConfig: {}

          # Photos S3 Origin
          - Id: PhotosS3Origin
            DomainName:
              Fn::Sub:
                - ${BucketName}.s3.${AWS::Region}.amazonaws.com
                - BucketName:
                    Fn::ImportValue: !Sub ${EnvironmentName}-okiteru-photos-bucket-name
            OriginAccessControlId: !Ref PhotosOAC
            S3OriginConfig: {}

          # API Gateway Origin
          - Id: ApiGatewayOrigin
            DomainName:
              Fn::Sub:
                - ${ApiId}.execute-api.${AWS::Region}.amazonaws.com
                - ApiId:
                    Fn::ImportValue: !Sub ${EnvironmentName}-okiteru-api-id
            OriginPath: !Sub /${EnvironmentName}
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

        # Default Cache Behavior (Frontend)
        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin
          ResponseHeadersPolicyId: 5cc3b908-e619-4b99-88e5-2cf7f45965bd # Managed-CORS-with-preflight-and-SecurityHeadersPolicy

        # Cache Behaviors
        CacheBehaviors:
          # API Cache Behavior
          - PathPattern: /api/*
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingDisabled
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac # Managed-AllViewerExceptHostHeader

          # Photos Cache Behavior
          - PathPattern: /photos/*
            TargetOriginId: PhotosS3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin

        # Custom Error Responses (SPA routing)
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300

        # Default Root Object
        DefaultRootObject: index.html

        # Logging (Optional)
        # Logging:
        #   Bucket: !Sub ${LoggingBucket}.s3.amazonaws.com
        #   Prefix: cloudfront/

      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-okiteru-distribution

Outputs:
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-cloudfront-id

  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-cloudfront-domain

  CloudFrontUrl:
    Description: CloudFront Distribution URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-cloudfront-url

  CustomDomainUrl:
    Condition: HasCustomDomain
    Description: Custom Domain URL
    Value: !Sub https://${CustomDomain}
    Export:
      Name: !Sub ${EnvironmentName}-okiteru-custom-domain-url
