version: 0.2

# CodeBuild用ビルド仕様
# 環境変数 ENV (development/staging/production) に応じてデプロイ先を切り替え

env:
  variables:
    NODE_VERSION: "18"
    PYTHON_VERSION: "3.11"
  parameter-store:
    # 環境ごとのシークレットをParameter Storeから取得
    DATABASE_URL: /okiteru/${ENV}/database-url
    COGNITO_USER_POOL_ID: /okiteru/${ENV}/cognito-user-pool-id
    COGNITO_CLIENT_ID: /okiteru/${ENV}/cognito-client-id
    S3_BUCKET_NAME: /okiteru/${ENV}/s3-bucket-name
    LAMBDA_FUNCTION_NAME: /okiteru/${ENV}/lambda-function-name
    CLOUDFRONT_DISTRIBUTION_ID: /okiteru/${ENV}/cloudfront-distribution-id
    API_URL: /okiteru/${ENV}/api-url
    PHOTOS_BUCKET_NAME: /okiteru/${ENV}/photos-bucket-name
    PHOTOS_BUCKET_URL: /okiteru/${ENV}/photos-bucket-url

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - echo "Environment: $ENV"

  pre_build:
    commands:
      - echo "Running pre-build phase..."

      # フロントエンド - Lint & Test
      - echo "Frontend - Installing dependencies..."
      - cd frontend
      - npm ci

      - echo "Frontend - Running lint..."
      - npm run lint || true # Lintエラーでも継続（警告として扱う）

      - echo "Frontend - Running tests..."
      - npm run test:ci || true # テストエラーでも継続（CI環境用）

      # バックエンド - Lint & Test
      - echo "Backend - Installing dependencies..."
      - cd ../backend
      - pip install -r requirements.txt -t .

      - echo "Backend - Running lint..."
      - ruff check app/ || true

      - echo "Backend - Running tests..."
      - pytest tests/ || true

  build:
    commands:
      - echo "Running build phase..."

      # フロントエンド - ビルド
      - echo "Frontend - Building..."
      - cd ../frontend
      # 環境変数をビルド時に設定
      - |
        echo "NEXT_PUBLIC_API_URL=${API_URL}" > .env.production
        echo "NEXT_PUBLIC_COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}" >> .env.production
        echo "NEXT_PUBLIC_COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}" >> .env.production
        echo "NEXT_PUBLIC_PHOTOS_BUCKET_URL=${PHOTOS_BUCKET_URL}" >> .env.production
        echo "NEXT_PUBLIC_ENVIRONMENT=${ENV}" >> .env.production
      - npm run build
      - echo "Frontend build completed"

      # バックエンド - Lambda用パッケージング
      - echo "Backend - Packaging for Lambda..."
      - cd ../backend
      - zip -r ../lambda-deployment.zip . -x "*.git*" -x "*__pycache__*" -x "*.pyc" -x "tests/*" -x "*.pytest_cache*"
      - echo "Backend packaging completed"

  post_build:
    commands:
      - echo "Running post-build phase..."

      # フロントエンド - S3へデプロイ
      - echo "Frontend - Deploying to S3..."
      - cd ../frontend
      - aws s3 sync out/ s3://${S3_BUCKET_NAME} --delete --cache-control "public, max-age=31536000, immutable"
      - echo "Frontend deployed to S3: s3://${S3_BUCKET_NAME}"

      # CloudFront キャッシュ無効化
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
      - echo "CloudFront cache invalidated"

      # バックエンド - Lambdaへデプロイ
      - echo "Backend - Deploying to Lambda..."
      - cd ..
      - aws lambda update-function-code --function-name ${LAMBDA_FUNCTION_NAME} --zip-file fileb://lambda-deployment.zip
      - echo "Backend deployed to Lambda: ${LAMBDA_FUNCTION_NAME}"

      # Lambda環境変数を更新
      - |
        aws lambda update-function-configuration \
          --function-name ${LAMBDA_FUNCTION_NAME} \
          --environment Variables="{
            DATABASE_URL=${DATABASE_URL},
            COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID},
            COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID},
            S3_BUCKET_NAME=${S3_BUCKET_NAME},
            PHOTOS_BUCKET_NAME=${PHOTOS_BUCKET_NAME},
            ENVIRONMENT=${ENV}
          }"

      - echo "Deployment completed successfully!"

artifacts:
  files:
    - "**/*"
  name: okiteru-build-$(date +%Y%m%d-%H%M%S)

cache:
  paths:
    - "frontend/node_modules/**/*"
    - "backend/.venv/**/*"
